checkout/urls.py
from django.urls import path 
from . views import checkout, payment, oderView

app_name = "checkout"

urlpatterns = [
	path('checkout/', checkout, name="index"),
	path('payment/', payment, name="payment"),
	# path('charge/', charge, name="charge"),
	path('my-orders/', oderView, name="oderView")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('products.urls', namespace='mainapp')),
                  path('', include('checkout.urls', namespace='checkout')),
                  path('', include('dashboard.urls', namespace='dash')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth import get_user_model


# Create your models here.

# Get the user model
User = get_user_model()


class ShippingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    landmark = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.user.username} shipping address'

    class Meta:
        verbose_name_plural = "Shipping Addresses"


# Address Form
class ShippingForm(ModelForm):
    class Meta:
        model = ShippingAddress
        fields = ['address', 'zipcode', 'city', 'landmark']

checkout/views.py
from django.utils.crypto import get_random_string
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from cart.models import Order, Cart
from .models import ShippingForm, ShippingAddress
from django.views.generic.base import TemplateView


def checkout(request):
    # Checkout view
    form = ShippingForm

    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order_items = order_qs[0].orderitems.all()
    order_total = order_qs[0].get_totals()
    context = {"form": form, "order_items": order_items, "order_total": order_total}
    # Getting the saved saved_address
    saved_address = ShippingAddress.objects.filter(user=request.user)
    if saved_address.exists():
        savedAddress = saved_address.first()
        context = {"form": form, "order_items": order_items, "order_total": order_total, "savedAddress": savedAddress}
    if request.method == "POST":
        saved_address = ShippingAddress.objects.filter(user=request.user)
        if saved_address.exists():

            savedAddress = saved_address.first()
            form = ShippingForm(request.POST, instance=savedAddress)
            if form.is_valid():
                shippingaddress = form.save(commit=False)
                shippingaddress.user = request.user
                shippingaddress.save()
        else:
            form = ShippingForm(request.POST)
            if form.is_valid():
                shippingaddress = form.save(commit=False)
                shippingaddress.user = request.user
                shippingaddress.save()

    return render(request, 'checkout/index.html', context)


def payment(request):
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    # start
    order = Order.objects.get(user=request.user, ordered=False)
    orderitems = order.orderitems.all()
    order_total = order_qs[0].get_totals()
    totalCents = float(order_total * 100);
    total = round(totalCents, 2)
    hello = "hey there"
    if request.method == 'POST':
        order.hello = "hey there"
        message = request.POST['message']
#         send_mail(f'{request.user} ',
        send_mail('New Order',
                  message,
                  settings.EMAIL_HOST_USER,
                  ['rahilkazi66@gmail.com'],
                  fail_silently=False)
        orderId = get_random_string(length=5,
                                    allowed_chars=u'abcdefhijklmnorstuvwxzABCDEFGHIJKLMNOPQRSTUVWXYZ')
        order.ordered = True
        order.orderId = f'{request.user}{orderId}'
        order.save()
        cartItems = Cart.objects.filter(user=request.user)
        for item in cartItems:
            item.purchased = True
            item.save()
            return redirect('checkout:oderView')
    return render(request, 'checkout/payment.html', {"total": total, "items": orderitems, "order": order})


def oderView(request):
    orders = Order.objects.filter(user=request.user, ordered=True)
    if orders.exists():
        return render(request, 'checkout/order.html', {'orders': orders})
    else:
        messages.warning(request, "You do not have an active order")
        return redirect('/')

def CancelOrder(request, pk):
    order = Order.objects.get(id=pk)
#     order = Order.objects.filter(user=request.user, ordered=True)
    order.delete()
    return redirect('checkout:oderView')
    contex = {}
    return render(request, 'checkout/order.html', contex)

checkout/templates/checkout/charge.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{%block title%}Dayout24 | Thank You{% endblock %}
{% block content %}


<div class="container mt-5 text-center">
<h2 class="text-center">Thanks, you for your Orders</h2>
<a href="/my-orders" class="btn btn-success">My Orders</a>
</div>

{% endblock %}

checkout/templates/checkout/index.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{%block title%}{% endblock %}
{% block content %}

<div class="container mt-5">
  <div class="row">
      {% if savedAddress %}
      <div class="card mb-5" style="height: auto">
      <h4>Saved Address</h4>
        <div class="card-body">
          <p><b>Address :</b> {{ savedAddress.address }}</p>
          <p><b>City :</b> {{ savedAddress.city }}</p>
          <p><b>Zipcode :</b> {{ savedAddress.zipcode }}</p>
          <p><b>Landmark :</b> {{ savedAddress.landmark }}</p>
        </div>
        <div class="card-body">
           <a href="{% url 'checkout:payment' %}" class="btn btn-primary float-right">Proceed to Checkout with the saved Address</a>
        </div>
      {% else %}
          <h2 class="mb-3">Shipping Address > <span class="text-muted">Checkout</span></h2>
          <div class="col-md-9">
     <div class="card mb-5" style="height: auto">


          <div class="card-body">
          <form method="POST">
          {% csrf_token %}

         {{ form | crispy}}
          <button type="submit" class="btn btn-primary float-right">Next</button>
          </form>
       </div>
      </div>
          </div>
      {% endif %}
    </div>
    <div class="col-md-3">
      <div class="card" style="height: auto">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            {% for item in order_items %}
            <li class="list-group-item">{{ item.item.name }} x {{ item.quantity }}</li>
            {% endfor %}
          </ul>
        </div>
           <div class="card-footer">
            <span class="float-left"><b>Order Total</b></span>
            <span class="float-right"><b>$ {{ order_total | floatformat:2 }}</b></span>
          </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

checkout/templates/checkout/order.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{%block title%}Dayout24 | Order{% endblock %}
{% block content %}


<div class="container mt-5">
<h2 class="text-center"><strong>Your Ordes</strong></h2>
<div class="row">
	<div class="col-md-12">
		<div class="card mt-5" style="height: auto">
			<div class="table-responsive">
			<table class="table">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Order Id</th>
			      <th scope="col">Products</th>
			      <th scope="col">Status</th>
			    </tr>
			  </thead>
			  <tbody>
			    
			    {% for order in orders %}
			    <tr>
			      <th scope="row">{{ forloop.counter }}</th>
					<td><a style="font-size: 15px" href="#">{{ order.orderId }}</a></td>
			      <td>
			      	{% for item in order.orderitems.all %}
			      		{{ item }}
			      		<br>
			      	{% endfor %}
			      </td>
			      <td><span class="badge badge-primary">{{ order.status }}</span></td>
     <td><a href="{% url 'checkout:cancel-order' order.id %}" class="btn btn-danger btn-sm" style="display:inline-block; position:absolute; right:26px; " > Cancel Order</a></td>
			  	</tr>
			      {% endfor %}
			    
			  </tbody>
			</table>
			</div>
		</div>
	</div>
	<div class="col-md-12 my-5 text-center">
		<a href="/" class="btn btn-success">Back to Home</a>
	</div>
</div>
</div>

{% endblock %}

checkout/templates/checkout/payment.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{%block title%}Dayout24 | Payment{% endblock %}
{% block content %}

<div class="container mt-5 text-center">
<h2>Pay with Stripe</h2>
<form action="{% url 'checkout:payment' %}" method="post">
  {% csrf_token %}
<input type="submit">
</form>

</div>

{% endblock %}