checkout/urls.py
from django.urls import path 
from . views import checkout, payment, oderView

app_name = "checkout"

urlpatterns = [
	path('checkout/', checkout, name="index"),
	path('payment/', payment, name="payment"),
	# path('charge/', charge, name="charge"),
	path('my-orders/', oderView, name="oderView")
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dash'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('cp/', views.createProduct, name='c-p'),  # for create product
    path('pl/', views.productlist, name='p-l'),  # for create product

    path('up/<str:pk>/', views.updateProduct, name='u-p'),  # for update product
    path('dp/<str:pk>/', views.deleteProduct, name='d-p'),  # for delete product

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('products.urls', namespace='mainapp')),
                  path('', include('checkout.urls', namespace='checkout')),
                  path('', include('dashboard.urls', namespace='dash')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart, addcart, Cart
from .views import home, ProductDetail, Home
from . import views
app_name = 'mainapp'

urlpatterns = [
    # path('', Home.as_view(), name='home'),
    path('', home, name='home'),
    path('p', Home.as_view(), name='home'),
    path('product/<slug>/', ProductDetail.as_view(), name='product'),
    path('cart/', CartView, name='cart-home'),
    path('cart/<id>', add_to_cart, name='cart'),
    path('addcart/<id>', addcart, name='addcart'),
    path('decrease-cart/<id>', decreaseCart, name='decrease-cart'),
    path('remove/<id>', remove_from_cart, name='remove-cart'),
    path('signup/', views.signupPage, name='signup'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    # path('dashboard/', views.dashboard, name='dashboard'),
]

products/models.py
from django.db import models
from django.urls import reverse
from cloudinary.models import CloudinaryField


# Category Model
class Category(models.Model):
    title = models.CharField(max_length=300)
    primaryCategory = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"


# Product Model
class Product(models.Model):
    mainimage = CloudinaryField('image', blank=True)
    name = models.CharField(max_length=300)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Detail Text')
    price = models.FloatField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("mainapp:product", kwargs={
            'slug': self.slug
        })

products/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

products/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from products.models import Product

from cart.decorators import login_register_check

from .filters import ProductFilter
from .forms import CreateUserForm

from django.contrib.auth import authenticate, login, logout


class Home(ListView):
    model = Product
    template_name = 'products/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ProductFilter(self.request.GET, queryset=self.get_queryset())
        return context


def home(request):
    product_list = Product.objects.all()
    product_filter = ProductFilter(request.GET, queryset=product_list)
    return render(request, 'products/home.html', {'filter': product_filter})


class ProductDetail(DetailView):
    model = Product


@login_register_check
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('mainapp:home')
        else:
            messages.info(request, 'Username Or Password is incorrect')
            return render(request, 'account/login.html')

    context = {}
    return render(request, 'account/login.html', context)


@login_register_check
def signupPage(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            forms = form.save(commit=False)
            forms.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created ' + user)
            return redirect('mainapp:login')

    context = {'form': form}
    return render(request, 'account/signup.html', context)


def logoutUser(request):
    logout(request)
    return redirect('mainapp:home')

products/templates/products/.ipynb_checkpoints/backup-checkpoint.html
{% extends 'products/base.html' %}

{% load static %}

{% load crispy_forms_tags %}
{%block title%}Dayout24{% endblock %}
{% block content %}

  <div class="container my-5">
  	<h2 class="my-5">Products</h2>
    <div class="row">
<!--    <div class="col-md-3">-->
<!--         <form method="get">-->
<!--            {{ filter.form| crispy }}-->
<!--            <button type="submit">Search</button>-->
<!--        </form>-->
<!--    </div>-->
    <div class="col-md-9">
		<div class="row">
			{% for product in filter.qs %}
		  <div class="col-md-6 col-sm-12 col-lg-4">
			<figure class="card card-product">
				<div class="img-wrap">
					<img src="{% static 'img/def.png' %}" style="width: 100%; height: 300px;">
				</div>
				<figcaption class="info-wrap">
					<h6 class="title text-dots"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>

					<div class="action-wrap">
						<a href="addcart/{{ product.id }}" class="btn btn-primary btn-sm"> Add to Cart </a>
<!--            			<a href="cart/" class="btn btn-primary btn-sm"> View Cart </a>-->
						<a href="remove/{{ product.slug }}" class="btn btn-danger btn-sm"> Remove</a>
						<!-- price-wrap.// -->
						 <div class="price-wrap h5">
							<span class="price-new">Rs.{{product.price| floatformat:2}}</span>
<!--							<del class="price-old">Rs.{{product.f_price}}</del>-->
						</div>
					</div> <!-- action-wrap -->
				</figcaption>
			</figure> <!-- card // -->
		</div> <!-- col // -->
      {% endfor %}
		</div>
	</div>
  </div>
  </div>
{% endblock %}







<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'images/favicon/site.webmanifest' %}">
  <title>{%block title%}{% endblock %}</title>
  <style>
  	.card{
  		    height: 350px;
  	}
  	.card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden; }
  .card-product .price-new, .card-product .price {
    margin-right: 5px; }
  .card-product .price-old {
    color: #999; }
  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center; }
    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover; }
      
      .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px; }
  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .title {
    margin-top: 0; }
  </style>
</head>
<body>
{% include 'products/navbar.html' %}


    {% if messages %}
    <div class="messages container mt-2">
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        </div>
        {% endfor %}
    </div>
  {% endif %}
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script>
  
</script>
</body>
</html>

products/templates/products/.ipynb_checkpoints/base-checkpoint.html
<!DOCTYPE html>
{% load static %}
{% load cart_tag %}
{% load i18n %}
{% load widget_tweaks %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="electornics" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
<!--        <link href="css/dashboard.css" rel="stylesheet" />-->
<style>
/*             @media (max-width: 400px) {
                body {
                    background-color: lightblue;
                }
            } */


    .sb-sidenav-menu {
    }
    
    .sb-sidenav-footer {
    
    }
    .card{
        height: 350px;
    }
    .card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden; }
  .card-product .price-new, .card-product .price {
    margin-right: 5px; }
  .card-product .price-old {
    color: #999; }
  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center; }
    .card-product .img-wrap img {
      max-height: 100%;
      max-width: 100%;
      object-fit: cover; }
      
      .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px; }
  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee; }
  .card-product .title {
    margin-top: 0; }
  a.nav-link{
      display:flex !important;
    }  
  .badge {
      margin-left:.3em !important;
      font-size:90% !important;
            }
    .logout{
        font-size:10px;
        padding:6px;
    }

    .user{
        margin-top:5px;
    }
    .progress{
        height:.3em;
    }
</style>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Dayout24</a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href=""><i class="fas fa-bars"></i></button>
            
            <!-- Navbar Search-->
            {% block bsh %}
            {% endblock bsh %}
            <!-- Navbar-->
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
                        <i class="fa fa-shopping-cart"></i> Cart
                        <span class="badge badge-light">{{ request.user | cart_total }}</span>
                    </a>
                </li>
            </ul>
             {% else %}
            <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
                    <i class="fa fa-shopping-cart"></i> Cart
                    <span class="badge badge-light">{{ request.user.is_anonymous | cart_total }}</span>
                </a>
            </li>
            </ul>
            
            {% endif %}
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Category</div>
                            <a class="nav-link" href="">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                
                                Mufasa Flavour
                            </a>
                        {% if request.user.is_authenticated %}
                            <div class="sb-sidenav-menu-heading">Account</div>
                            {% if request.user.is_superuser %}
                            <a class="nav-link" href="{% url 'dash:dashboard'%}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            {% endif %}
                            <a class="nav-link" href="{% url 'checkout:oderView' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                My Order
                            </a>
                             <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
                                <div class="sb-nav-link-icon"><i class="fa fa-shopping-cart"></i></div>
                                My Cart
                            </a>
                            
                            {% else %}
                             <div class="sb-sidenav-menu-heading">Account</div>
                            <a class="nav-link" href="{% url 'mainapp:cart-home' %}" >
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                My Order
                            </a>
                             <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
                                <div class="sb-nav-link-icon"><i class="fa fa-shopping-cart"></i></div>
                                My Cart
                            </a>
                            <a class="nav-link" href="##">
                                Login Or SignUp First 
                            </a>
                            
                             {% endif %}                            
                        </div>
                    </div>
                  {% if request.user.is_authenticated %}
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        <div class="d-inline-block user">
                            <span class="text-capitalize">{{ request.user.username }}</span>
                        </div>
                        <!--           <div class="float-right"> -->
                        <a class="btn btn-primary logout float-right"  href="{% url 'mainapp:logout' %}"> logout </a>
                        <!--                         </div> -->
                    </div>
                    {% else %}
                    <div class="sb-sidenav-footer">
                        <a  class="btn btn-primary" href="login/">Login / Register</a>
                    </div>
                    {% endif %}
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="progress">
                                <div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                    <div class="container-fluid">
                        {% if messages %}
                        <div class="messages container mt-2">
                            {% for message in messages %}
                            <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% block sh %}{% endblock sh %}
                    </div>

                    {% block content %}
                    {% endblock %}
                    
                    {% block prod %}
                    {% endblock %}
                    


                </main>
                {% block footer %}
                {% endblock %}
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'dashboard/js/dashboard.js' %}"></script>
    </body>
</html>

products/templates/products/.ipynb_checkpoints/bsh-checkpoint.html
{% load widget_tweaks %}

<form method="get" class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
    <div class="input-group">
        {{ filter.form.name|add_class:'form-control'|attr:'aria-label:Search'|attr:'aria-describedby:basic-addon2'|attr:'placeholder:Search for...'|attr:'input' }}
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit"> <i class="fas fa-search"></i></button> 
        </div>
    </div>
</form>

products/templates/products/.ipynb_checkpoints/footer-checkpoint.html
  <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Dayout24 2020</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>

products/templates/products/.ipynb_checkpoints/home-checkpoint.html
{% extends 'products/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{%block title%}Dayout24{% endblock %}
<style>
	img {
		margin: 30px;

	}
</style>
{% block sh %}
{% include 'products/sh.html' %}
{% endblock sh %}

{% block bsh %}
{% include 'products/bsh.html' %}
{% endblock bsh %}

{% block footer %}
{% include 'products/footer.html' %}
{% endblock %}


{% block content %}



<div class="container my-5">
<!-- 	<h2 class="my-5">Products</h2> -->
	<div class="row">
<!-- 			<form method="get">
				{{ filter.form| crispy }}
				<button type="submit">Search</button>
			</form> -->
		<div class="col-md-9">
			<div class="row">
				{% for product in filter.qs %}
				<div class="col-md-6 col-sm-12 col-lg-4">
					<figure class="card card-product">
						<div class="img-wrap">
							<img src="{{ product.mainimage.url }}">
						</div>
						<figcaption class="info-wrap">
							<h6 class="title text-dots"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>
<!--                             <h6 class="title text-dots"><a href="#">{{ product.name }}</a></h6> -->
							<div class="action-wrap">
								<a href="addcart/{{ product.id }}" class="btn btn-primary btn-sm"> Add to Cart </a>
								<!--            			<a href="cart/" class="btn btn-primary btn-sm"> View Cart </a>-->
								<a href="remove/{{ product.id }}" class="btn btn-danger btn-sm"> Remove</a>
								<!-- price-wrap.// -->
								<div class="price-wrap h5">
									<span class="price-new">Rs.{{product.price| floatformat:2}}</span>
									<!--							<del class="price-old">Rs.{{product.f_price}}</del>-->
								</div>
							</div>
							<!-- action-wrap -->
						</figcaption>
					</figure>
					<!-- card // -->
				</div>
				<!-- col // -->
				{% endfor %}
			</div>
		</div>
	</div>
</div>


{% endblock %}

products/templates/products/.ipynb_checkpoints/navbar-checkpoint.html
{% load cart_tag %}

{% load i18n %}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <a class="navbar-brand" href="/">Dayout24</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li {% if request.path == 'contact' %}class="nav-item active"{% else %}class="nav-item"{% endif %}>
        <a class="nav-link" href="#">Men <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Women</a>
      </li>

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
          <i class="fa fa-shopping-cart"></i> Cart
          <span class="badge badge-light">{{ request.user | cart_total }}</span>
        </a>
      </li>
       <li class="nav-item">
        
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-tie"></i> {{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.user.is_superuser %}
          <a class="dropdown-item" href="{% url 'dash:dashboard' %}">Dashboard</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'checkout:oderView' %}">Orders</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'mainapp:logout' %}"> logout </a>
        </div>
      </li>
      {% else %}
      <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
          <i class="fa fa-shopping-cart"></i> Cart
          <span class="badge badge-light">{{ request.user.is_anonymous | cart_total }}</span>
        </a>
       <li class="nav-item">
        <a  class="btn btn-primary" href="login/">Login / Register</a>
      </li>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>

products/templates/products/.ipynb_checkpoints/product_detail-checkpoint.html
{% extends 'products/base.html' %}
{%load static%}

{%block title%}Dayout24{% endblock %}


{% block prod %}

<style>
    .img {
        height: 350px;
        width: 370px;
    }
     @media (max-width: 400px) {
         .img {
             height: 350px;
             width: 330px;
         }
    }
    .p-5 {
    padding: 1rem!important;
    }
</style>

<div class="container my-5">

	
<div class="card">
	<div class="row">
		<aside class="col-sm-4 border-right">
<article class="gallery-wrap"> 
<div class="img-big-wrap">
<!--  <div> <a href="#"><img src="/media/{{ object.mainimage }}" style="width: 450px"></a></div>-->
  <a href="#"><img class="img" src="{{ product.mainimage.url }}"></a>
</div> <!-- slider-product.// -->
</article> <!-- gallery-wrap .end// -->
		</aside>
		<aside class="col-sm-7">
<article class="card-body p-5">
	<h3 class="title mb-3">{{ object.name }}</h3>
<p class="price-detail-wrap"> 
	<span class="price h3 text-warning"> 
		<span class="currency">Rs.</span><span class="num">{{ object.price }}</span>
	</span> 
	
</p> <!-- price-detail-wrap .// -->
<dl class="item-property">
  <dt>Description</dt>
  <dd><p>{{ object.preview_text }}</p></dd>
</dl>

	<a href="{% url 'mainapp:addcart' object.id %}" class="btn btn-lg btn-outline-primary text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to cart </a>
</article> <!-- card-body.// -->
		</aside> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->


</div>
<!--container.//-->
{% endblock %}

products/templates/products/.ipynb_checkpoints/sh-checkpoint.html
{% load widget_tweaks %}


<form method="get" class="d-block d-xl-none d-lg-none d-md-none form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
    <div class="input-group">
        {{ filter.form.name|add_class:'form-control'|attr:'aria-label:Search'|attr:'aria-describedby:basic-addon2'|attr:'placeholder:Search for...'|attr:'input' }}
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit"> <i class="fas fa-search"></i></button> 
        </div>
    </div>
</form>